spring:
  application:
    name: addidas-challenge
  datasource:
#    driver-class: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/challenge?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
#    password: password
    driver-class: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS challenge
  jpa:
    show-sql:  true
    hibernate:
      ddl-auto: none